<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/SOAPWebService/SharedResources/Schemas/ReqRes.xsd" xmlns:tns="http://xmlns.example.com/1566241143702" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1566241143702">
    <import namespace="http://www.tibco.com/schemas/SOAPWebService/SharedResources/Schemas/ReqRes.xsd" location="../Schemas/ReqRes.xsd"/>
    <message name="InMessage">
        <part name="part1" element="ns:Req"/>
    </message>
    <message name="OutMessage">
        <part name="part1" element="ns:Res"/>
    </message>
    <portType name="PortType">
        <operation name="Operation">
            <input message="tns:InMessage"/>
            <output message="tns:OutMessage"/>
        </operation>
    </portType>
</definitions>